<?php

use Magelearn\Categoryfaq\ViewModel\Questions;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
$viewModel = $block->getData('viewModel');
$items = $viewModel->getItems();
?>
<div class="container">
    <?php foreach ($items as $question): ?>
    <div class="accordion">
        <div class="accordion-item">
            <a><?php echo $question->getTitle(); ?></a>
            <div class="content">
                <?php echo $question->getAnswer();
                $categoryHtml = $viewModel->getQuestionCategoryHtml($question);
                ?>
                <?php if ($categoryHtml && $categoryHtml != '') : ?>
                	<?php echo '<p><b><i>Categories: '.$categoryHtml.'</i></b></p>' ?>
                <?php endif; ?>
            </div>
        </div>
    <?php endforeach; ?>
    </div>
</div>
<script>
    require(['jquery', 'jquery/ui'], function($) {
        items = document.querySelectorAll(".accordion a");

        function toggleAccordion(){
            this.classList.toggle('active');
            this.nextElementSibling.classList.toggle('active');
        }

        items.forEach(item => item.addEventListener('click', toggleAccordion));
    });
</script>